import type { Project, Sprint, WorkItem } from '../types'

export const SEED_PROJECTS: Project[] = [
  {
    id: 'demo-p1',
    name: 'Habit Tracker App',
    description: 'Mobile app for daily habit tracking with streaks and progress charts',
    color: '7',
    pos: 0,
  },
  {
    id: 'demo-p2',
    name: 'REST API Backend',
    description: 'Node.js API powering the mobile app',
    color: '2',
    pos: 1,
  },
]

export const SEED_SPRINTS: Sprint[] = [
  // Habit Tracker – Sprint 1 (completed)
  {
    id: 'demo-s1',
    projectId: 'demo-p1',
    name: 'Sprint 1 – Foundation',
    description: 'Auth flow, navigation shell, and core data models',
    startDate: '2026-04-01',
    endDate: '2026-04-14',
    status: 'completed',
  },
  // Habit Tracker – Sprint 2 (active)
  {
    id: 'demo-s2',
    projectId: 'demo-p1',
    name: 'Sprint 2 – Core Features',
    description: 'Habit tracking, streak counters, and progress charts',
    startDate: '2026-04-15',
    endDate: '2026-04-28',
    status: 'active',
  },
  // Habit Tracker – Sprint 3 (planned)
  {
    id: 'demo-s3',
    projectId: 'demo-p1',
    name: 'Sprint 3 – Polish & Launch',
    description: 'Push notifications, onboarding, and app store submission',
    startDate: '2026-04-29',
    endDate: '2026-05-12',
    status: 'planned',
  },
  // API Backend – Sprint 1 (active)
  {
    id: 'demo-s4',
    projectId: 'demo-p2',
    name: 'Sprint 1 – v1.0 Release',
    description: 'Auth endpoints, habits CRUD, and deployment pipeline',
    startDate: '2026-04-15',
    endDate: '2026-04-28',
    status: 'active',
  },
]

export const SEED_ITEMS: WorkItem[] = [
  // ── Habit Tracker / Sprint 1 (all closed) ──────────────────────────────
  {
    id: 'demo-w1',
    projectId: 'demo-p1',
    sprintId: 'demo-s1',
    title: 'Initialize React Native + Expo project',
    description: 'Bootstrap with TypeScript template and configure ESLint',
    type: 'task',
    status: 'closed',
    priority: 'high',
    storyPoints: 2,
    assignee: 'Alex',
    deadline: '',
  },
  {
    id: 'demo-w2',
    projectId: 'demo-p1',
    sprintId: 'demo-s1',
    title: 'Implement email/password authentication',
    description: 'JWT-based auth with refresh tokens stored in SecureStore',
    type: 'feature',
    status: 'closed',
    priority: 'high',
    storyPoints: 8,
    assignee: 'Alex',
    deadline: '',
  },
  {
    id: 'demo-w3',
    projectId: 'demo-p1',
    sprintId: 'demo-s1',
    title: 'Design habit and completion data models',
    description: 'Schema covering habits, daily completions, and streak metadata',
    type: 'task',
    status: 'closed',
    priority: 'medium',
    storyPoints: 3,
    assignee: 'Sam',
    deadline: '',
  },
  {
    id: 'demo-w4',
    projectId: 'demo-p1',
    sprintId: 'demo-s1',
    title: 'Build bottom-tab navigation shell',
    description: 'Today, Stats, and Settings tabs with placeholder screens',
    type: 'feature',
    status: 'closed',
    priority: 'medium',
    storyPoints: 3,
    assignee: 'Sam',
    deadline: '',
  },

  // ── Habit Tracker / Sprint 2 (active – mixed states) ───────────────────
  {
    id: 'demo-w5',
    projectId: 'demo-p1',
    sprintId: 'demo-s2',
    title: 'Daily check-in screen with habit cards',
    description: 'Swipeable cards per habit; tap to mark complete',
    type: 'feature',
    status: 'active',
    priority: 'high',
    storyPoints: 5,
    assignee: 'Alex',
    deadline: '2026-04-22',
  },
  {
    id: 'demo-w6',
    projectId: 'demo-p1',
    sprintId: 'demo-s2',
    title: 'Streak counter and longest-streak tracking',
    description: 'Calculate current and all-time streaks per habit',
    type: 'feature',
    status: 'active',
    priority: 'high',
    storyPoints: 5,
    assignee: 'Sam',
    deadline: '',
  },
  {
    id: 'demo-w7',
    projectId: 'demo-p1',
    sprintId: 'demo-s2',
    title: 'Weekly progress bar chart',
    description: 'Recharts bar chart showing completion rate by day of week',
    type: 'feature',
    status: 'new',
    priority: 'medium',
    storyPoints: 8,
    assignee: '',
    deadline: '',
  },
  {
    id: 'demo-w8',
    projectId: 'demo-p1',
    sprintId: 'demo-s2',
    title: 'Fix: habit not saving on first tap',
    description: 'Race condition between optimistic UI update and API call',
    type: 'bug',
    status: 'resolved',
    priority: 'high',
    storyPoints: 2,
    assignee: 'Alex',
    deadline: '',
  },
  {
    id: 'demo-w9',
    projectId: 'demo-p1',
    sprintId: 'demo-s2',
    title: 'Habit creation form',
    description: 'Name, icon picker, color, and repeat frequency fields',
    type: 'feature',
    status: 'new',
    priority: 'medium',
    storyPoints: 3,
    assignee: '',
    deadline: '',
  },
  {
    id: 'demo-w10',
    projectId: 'demo-p1',
    sprintId: 'demo-s2',
    title: 'Offline persistence with AsyncStorage',
    description: 'Cache habits and completions locally for offline use',
    type: 'task',
    status: 'new',
    priority: 'high',
    storyPoints: 3,
    assignee: 'Sam',
    deadline: '',
  },

  // ── Habit Tracker / Sprint 3 (planned – all new) ────────────────────────
  {
    id: 'demo-w11',
    projectId: 'demo-p1',
    sprintId: 'demo-s3',
    title: 'Daily push notification reminders',
    description: 'Scheduled local notifications at user-configured times',
    type: 'feature',
    status: 'new',
    priority: 'high',
    storyPoints: 8,
    assignee: '',
    deadline: '',
  },
  {
    id: 'demo-w12',
    projectId: 'demo-p1',
    sprintId: 'demo-s3',
    title: '3-screen onboarding flow for new users',
    description: 'Welcome, habit selection, and notification permission prompts',
    type: 'feature',
    status: 'new',
    priority: 'medium',
    storyPoints: 5,
    assignee: '',
    deadline: '',
  },
  {
    id: 'demo-w13',
    projectId: 'demo-p1',
    sprintId: 'demo-s3',
    title: 'App Store and Play Store screenshots',
    description: 'Generate device-framed screenshots for both storefronts',
    type: 'task',
    status: 'new',
    priority: 'low',
    storyPoints: 2,
    assignee: '',
    deadline: '',
  },
  {
    id: 'demo-w14',
    projectId: 'demo-p1',
    sprintId: 'demo-s3',
    title: 'Performance audit and bundle size reduction',
    description: 'Profile startup time and eliminate unused dependencies',
    type: 'task',
    status: 'new',
    priority: 'medium',
    storyPoints: 3,
    assignee: '',
    deadline: '',
  },

  // ── Habit Tracker / Backlog ─────────────────────────────────────────────
  {
    id: 'demo-w15',
    projectId: 'demo-p1',
    sprintId: '',
    title: 'Social sharing – share streaks to Instagram Stories',
    description: 'Generate a shareable graphic showing current streak',
    type: 'feature',
    status: 'new',
    priority: 'low',
    storyPoints: 13,
    assignee: '',
    deadline: '',
  },
  {
    id: 'demo-w16',
    projectId: 'demo-p1',
    sprintId: '',
    title: 'Dark / light mode respecting system preference',
    description: 'Use react-navigation theme tokens and system color scheme',
    type: 'feature',
    status: 'new',
    priority: 'low',
    storyPoints: 5,
    assignee: '',
    deadline: '',
  },

  // ── API Backend / Sprint 1 ──────────────────────────────────────────────
  {
    id: 'demo-w17',
    projectId: 'demo-p2',
    sprintId: 'demo-s4',
    title: 'POST /auth/register and /auth/login endpoints',
    description: 'bcrypt password hashing, JWT issuance, and refresh logic',
    type: 'feature',
    status: 'resolved',
    priority: 'high',
    storyPoints: 5,
    assignee: 'Jordan',
    deadline: '',
  },
  {
    id: 'demo-w18',
    projectId: 'demo-p2',
    sprintId: 'demo-s4',
    title: 'Habits CRUD REST endpoints',
    description: 'GET /habits, POST, PATCH, DELETE with owner-only authorization',
    type: 'feature',
    status: 'active',
    priority: 'high',
    storyPoints: 8,
    assignee: 'Jordan',
    deadline: '',
  },
  {
    id: 'demo-w19',
    projectId: 'demo-p2',
    sprintId: 'demo-s4',
    title: 'Docker Compose dev environment',
    description: 'Postgres + Node containers with hot-reload via nodemon',
    type: 'task',
    status: 'closed',
    priority: 'medium',
    storyPoints: 3,
    assignee: 'Jordan',
    deadline: '',
  },
  {
    id: 'demo-w20',
    projectId: 'demo-p2',
    sprintId: 'demo-s4',
    title: 'CI/CD pipeline via GitHub Actions',
    description: 'Lint, test, and deploy to Railway on every push to main',
    type: 'task',
    status: 'new',
    priority: 'medium',
    storyPoints: 5,
    assignee: '',
    deadline: '',
  },
]
